# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\"\x1c\n\tHeartbeat\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x10HeartbeatService\x12(\n\x0cHeartbeatRPC\x12\n.Heartbeat\x1a\n.Heartbeat\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEAT._serialized_start=19
  _HEARTBEAT._serialized_end=47
  _HEARTBEATSERVICE._serialized_start=49
  _HEARTBEATSERVICE._serialized_end=109
# @@protoc_insertion_point(module_scope)
